development: &defaults
  adapter: mysql
  database: tefter_development
  username: root
  password:
  encoding: utf8

test: &TEST
  <<: *defaults
  database: tefter_test

cucumber:
  <<: *TEST

staging:
  <<: *defaults
  database: tefter_staging

production:
  <<: *defaults
  database: tefter_production
